[package]
name = "nimbus"
description = "Slave server status checker with cronjob"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

